version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass